-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              "name" varchar NOT NULL,
                              phone_number varchar(15) NOT NULL,
                              registered_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              active bool DEFAULT true NOT NULL,
                              "uuid" uuid NOT NULL,
                              updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT users_pk PRIMARY KEY (id),
                              CONSTRAINT users_unique UNIQUE (uuid)
);

-- public.user_scores definition
-- Drop table
-- DROP TABLE public.user_scores;
CREATE TABLE public.user_scores (
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    user_id int8 NOT NULL,
                                    communication int4 DEFAULT 0 NOT NULL,
                                    cleanning int4 DEFAULT 0 NOT NULL,
                                    punctuality int4 DEFAULT 0 NOT NULL,
                                    cordiality int4 DEFAULT 0 NOT NULL,
                                    total_score numeric(2, 1) DEFAULT 0.0 NOT NULL,
                                    registered_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                    "comments" varchar NOT NULL,
                                    active bool DEFAULT true NOT NULL,
                                    CONSTRAINT user_scores_pk PRIMARY KEY (id),
                                    CONSTRAINT user_scores_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);