-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              "name" varchar NOT NULL,
                              phone_number varchar(15) NOT NULL,
                              registered_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              active bool DEFAULT true NOT NULL,
                              "uuid" uuid NOT NULL,
                              updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT users_pk PRIMARY KEY (id),
                              CONSTRAINT users_unique UNIQUE (uuid)
);